# Generated by Django 3.2.7 on 2021-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clicl Link Above To Read The Blog Post...', max_length=255),
        ),
    ]
