# Generated by Django 3.2.7 on 2021-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click The Link Above To Read The Blog Post...', max_length=255),
        ),
    ]
